inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "vendor/**/*"
    - "spec/unit/fixtures/**/*"
    - "tmp/**/*"
    - "lib/qansible_init/templates/**/*"
    - "qansible.gemspec"
    - "lib/qansible/commands/init/templates/**/*"
  TargetRubyVersion: 2.1
  DisplayCopNames: true

  # the default CacheRootDirectory is no longer `/tmp`, but a directory under
  # `$HOME` and some Unix platforms use symlink to that path
  AllowSymlinksInCacheRootDirectory: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/SpaceInsideBrackets:
  Enabled: false

Style/FormatString:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Lint/UnneededDisable:
  Exclude:
    - "lib/qansible/commands/init/templates/tests/integration/example/spec/spec_helper.rb"
