inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "vendor/**/*"
    - "spec/unit/fixtures/**/*"
    - "tmp/**/*"
    - "lib/qansible_init/templates/**/*"
    - "qansible.gemspec"
  TargetRubyVersion: 2.1
  DisplayCopNames: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpaceInsideBrackets:
  Enabled: false

Style/FormatString:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Lint/UnneededDisable:
  Exclude:
    - "lib/qansible/commands/init/templates/tests/integration/example/spec/spec_helper.rb"
