#!/usr/bin/env ruby

require "pathname"
require "qansible"

def main
  command = ARGV.shift
  program = Pathname.new(__FILE__).basename
  runner = nil
  case command
  when "init"
    option = Qansible::Parser::Init.parse ARGV
    runner = Qansible::Command::Init.new(option)
  when "qa"
    option = Qansible::Parser::QA.parse ARGV
    runner = Qansible::Command::QA.new(option)
  when "--help"
    puts "Usage: %s COMMAND [OPTIONS]" % [program]
    puts "%s COMMAND [OPTIONS]" % [program]
    puts "%s COMMAND --help" % [program]
    puts ""
    puts "Available commands:"
    puts "  qa"
    puts "  init"
    exit
  when "--version"
    puts Qansible::VERSION
    exit
  when "commands"
    puts "qa"
    puts "init"
    exit
  else
    puts "unknown command `%s`" % [command]
    exit 1
  end

  runner.run
end

main
