source "https://rubygems.org"

gem "infrataster", "~> 0.3.2", git: "https://github.com/trombik/infrataster.git", branch: "reallyenglish"
gem "kitchen-ansible", "~> 0.48"
gem "kitchen-sync", "~> 2.1.1", git: "https://github.com/trombik/kitchen-sync.git", branch: "without_full_path_to_rsync"
gem "kitchen-vagrant", "~> 0.20.0"
gem "kitchen-verifier-shell", "~> 0.2.0"
gem "rake", "~> 11.1.2"
gem "rspec", "~> 3.4.0"
gem "rspec-retry", "~> 0.5.6"
gem "rubocop", "~> 0.52.1"
gem "serverspec", "~> 2.41.1"
gem "specinfra", ">= 2.73.1"
gem "test-kitchen", "~> 1.6.0"
