---
name: build
on:
  - pull_request
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Setup git-config
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Run rake
        run: |
          bundle exec rake

      - name: Try rake install
        run: |
          bundle exec rake install
